[tool.poetry]
name = "lavague-example"
version = "0.1.0"
description = ""
authors = ["Chandler Roth <hey@chandlerroth.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
lavague = "^1.1.19"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
